[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    # OpenZeppelin from lib
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

optimizer = true
optimizer_runs = 200
via_ir = true

# RPC endpoints
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan API key for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
